/**
 * Verify that JS serialization matches Rust reference bytes exactly.
 * Reference values generated by: cargo run --example reference_bytes
 *
 * Run with: node test/reference.test.js
 */

import { PostcardEncoder } from '../src/postcard.js';
import { frameBytes } from '../src/framing.js';
import { Commands, encodeConfiguration, encodeFlux, ConfigurationType } from '../src/message.js';

let passed = 0;
let failed = 0;

function assertHex(actual, expected, label) {
  const actualHex = Array.from(actual).map(b => b.toString(16).padStart(2, '0')).join('');
  if (actualHex === expected) {
    passed++;
    console.log(`PASS: ${label}`);
  } else {
    failed++;
    console.error(`FAIL: ${label}`);
    console.error(`  expected: ${expected}`);
    console.error(`  actual:   ${actualHex}`);
    // Show byte-by-byte diff
    const expBytes = expected.match(/.{2}/g) || [];
    const actBytes = actualHex.match(/.{2}/g) || [];
    const maxLen = Math.max(expBytes.length, actBytes.length);
    for (let i = 0; i < maxLen; i++) {
      const e = expBytes[i] || '--';
      const a = actBytes[i] || '--';
      if (e !== a) {
        console.error(`  byte ${i}: expected ${e}, got ${a}`);
      }
    }
  }
}

// Known UUIDs matching the Rust test
const ID_ONES = new Uint8Array(16).fill(0x01);
const RESOURCE_ZEROS = new Uint8Array(16).fill(0x00);

/**
 * Build a full framed Message::Command manually matching the Rust structure.
 * Message::Command = variant 0
 * CommandMessage { identifier, context, resource, command }
 */
function buildTestMessage(identifier, context, resource, commandBytes) {
  const enc = new PostcardEncoder();

  // Message::Command = variant 0
  enc.enumVariant(0);

  // CommandMessage.identifier
  enc.uuid(identifier);

  // CommandMessage.context: Option<Identifier>
  enc.option(context, (e, v) => e.uuid(v));

  // CommandMessage.resource: Option<Identifier>
  enc.option(resource, (e, v) => e.uuid(v));

  // CommandMessage.command (raw bytes from Commands.*)
  for (const b of commandBytes) enc.buf.push(b);

  return frameBytes(enc.result());
}

// Reference hex from Rust: cargo run --example reference_bytes
const RUST_HOST_INFO = '02001010010101010101010101010101010101010000010003';
const RUST_FIXTURE_COUNT = '02001010010101010101010101010101010101010001101000000000000000000000000000000000010103';
const RUST_EMITTER_FLUX_SET = '02001010010101010101010101010101010101010001101000000000000000000000000000000000061002000000003f03';

// Test 1: HOST_INFO
{
  const msg = buildTestMessage(ID_ONES, null, null, Commands.hostInfo());
  assertHex(msg, RUST_HOST_INFO, 'HOST_INFO');
}

// Test 2: FIXTURE_COUNT
{
  const msg = buildTestMessage(ID_ONES, null, RESOURCE_ZEROS, Commands.hostFixtureCount());
  assertHex(msg, RUST_FIXTURE_COUNT, 'FIXTURE_COUNT');
}

// Test 3: EMITTER_FLUX_SET
{
  const msg = buildTestMessage(ID_ONES, null, RESOURCE_ZEROS, Commands.emitterFluxSet({ value: 0.5 }));
  assertHex(msg, RUST_EMITTER_FLUX_SET, 'EMITTER_FLUX_SET');
}

console.log(`\nResults: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
